swagger: "2.0"
info:
  description: "Trex description"
  version: "1.0.0"
  title: "Trex"
host: localhost
basePath: /trex/api
tags:
- name: "books"
  description: "Search for books"
- name: "videos"
  description: "Search for videos"
- name: "presentations"
  description: "Search for presentations"
- name: "articles"
  description: "Search for articles"
schemes:
- "http"
paths:
  /books:
    get:
      tags:
      - "books"
      summary: "Search for books"
      description: "Search for books"
      operationId: "getBooks"
      consumes:
      - "*/*"
      produces:
      - "application/json"
      parameters:
        - in: "query"
          name: "terms"
          type: string
          required: true
          description: "The keywords to search for"
        - in: "query"
          name: "language"
          type: string
          description: "The language of the books"
        - in: "query"
          name: "minimumRating"
          type: number
          description: "The minimum rating of the books"
        - in: "query"
          name: "from"
          type: number
          description: "The starting year of the books"
        - in: "query"
          name: "to"
          type: number
          description: "The final year of the books"
      responses:
        200:
          description: "successful operation"
          schema:
             $ref: "#/definitions/BooksResponse"
        400:
          description: "Invalid status value"
        405:
          description: "Invalid input"
definitions:
    Resource:
        type: "object"
        properties:
            type:
                type: "string"
            title:
                type: "string"
            description:
                type: "string"
            authors:
                type: "array"
                items:
                    type: "object"
            image:
                type: "string"
            tags:
                type: "array"
                items:
                    type: "object"
            rating:
                type: "number"
            date:
                type: "string"
            language:
                type: "string"
            url:
                type: "string"

    BooksResponse:
        type: "object"
        properties:
          books:
            type: "array"
            items:
                $ref: "#/definitions/Resource"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
